# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.16 on 2018-10-26 17:22
=======
# Generated by Django 1.11.14 on 2018-07-29 12:28
>>>>>>> 48922223700d96126052678f09c9dfebc762821f
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
<<<<<<< HEAD
import django.utils.timezone
=======
>>>>>>> 48922223700d96126052678f09c9dfebc762821f


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
<<<<<<< HEAD
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
=======
                ('created_date', models.DateTimeField(blank=True, null=True)),
>>>>>>> 48922223700d96126052678f09c9dfebc762821f
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
